
#################
###  GLFW
#################
set(CONAN_GLFW_ROOT_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc")
set(CONAN_INCLUDE_DIRS_GLFW_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/include")
set(CONAN_LIB_DIRS_GLFW_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/lib")
set(CONAN_BIN_DIRS_GLFW_RELEASE )
set(CONAN_RES_DIRS_GLFW_RELEASE )
set(CONAN_SRC_DIRS_GLFW_RELEASE )
set(CONAN_BUILD_DIRS_GLFW_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/")
set(CONAN_FRAMEWORK_DIRS_GLFW_RELEASE )
set(CONAN_LIBS_GLFW_RELEASE glfw3)
set(CONAN_PKG_LIBS_GLFW_RELEASE glfw3)
set(CONAN_SYSTEM_LIBS_GLFW_RELEASE gdi32)
set(CONAN_FRAMEWORKS_GLFW_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_GLFW_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_GLFW_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLFW_RELEASE )

set(CONAN_C_FLAGS_GLFW_RELEASE "")
set(CONAN_CXX_FLAGS_GLFW_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLFW_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLFW_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE "${CONAN_FRAMEWORKS_GLFW_RELEASE}" "_GLFW" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_GLFW_RELEASE ${CONAN_PKG_LIBS_GLFW_RELEASE} ${CONAN_SYSTEM_LIBS_GLFW_RELEASE} ${CONAN_FRAMEWORKS_FOUND_GLFW_RELEASE})


#################
###  GLAD
#################
set(CONAN_GLAD_ROOT_RELEASE "C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb")
set(CONAN_INCLUDE_DIRS_GLAD_RELEASE "C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/include")
set(CONAN_LIB_DIRS_GLAD_RELEASE "C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/lib")
set(CONAN_BIN_DIRS_GLAD_RELEASE )
set(CONAN_RES_DIRS_GLAD_RELEASE )
set(CONAN_SRC_DIRS_GLAD_RELEASE )
set(CONAN_BUILD_DIRS_GLAD_RELEASE "C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/")
set(CONAN_FRAMEWORK_DIRS_GLAD_RELEASE )
set(CONAN_LIBS_GLAD_RELEASE glad)
set(CONAN_PKG_LIBS_GLAD_RELEASE glad)
set(CONAN_SYSTEM_LIBS_GLAD_RELEASE )
set(CONAN_FRAMEWORKS_GLAD_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_GLAD_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_GLAD_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_GLAD_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_GLAD_RELEASE )

set(CONAN_C_FLAGS_GLAD_RELEASE "")
set(CONAN_CXX_FLAGS_GLAD_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_GLAD_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_GLAD_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_GLAD_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_GLAD_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_GLAD_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_GLAD_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_GLAD_RELEASE "${CONAN_FRAMEWORKS_GLAD_RELEASE}" "_GLAD" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_GLAD_RELEASE ${CONAN_PKG_LIBS_GLAD_RELEASE} ${CONAN_SYSTEM_LIBS_GLAD_RELEASE} ${CONAN_FRAMEWORKS_FOUND_GLAD_RELEASE})


#################
###  OPENGL
#################
set(CONAN_OPENGL_ROOT_RELEASE "C:/Users/thoma/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9")
set(CONAN_INCLUDE_DIRS_OPENGL_RELEASE )
set(CONAN_LIB_DIRS_OPENGL_RELEASE )
set(CONAN_BIN_DIRS_OPENGL_RELEASE )
set(CONAN_RES_DIRS_OPENGL_RELEASE )
set(CONAN_SRC_DIRS_OPENGL_RELEASE )
set(CONAN_BUILD_DIRS_OPENGL_RELEASE "C:/Users/thoma/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/")
set(CONAN_FRAMEWORK_DIRS_OPENGL_RELEASE )
set(CONAN_LIBS_OPENGL_RELEASE )
set(CONAN_PKG_LIBS_OPENGL_RELEASE )
set(CONAN_SYSTEM_LIBS_OPENGL_RELEASE opengl32)
set(CONAN_FRAMEWORKS_OPENGL_RELEASE )
set(CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_OPENGL_RELEASE )
set(CONAN_BUILD_MODULES_PATHS_OPENGL_RELEASE )
# COMPILE_DEFINITIONS are equal to CONAN_DEFINES without -D, for targets
set(CONAN_COMPILE_DEFINITIONS_OPENGL_RELEASE )

set(CONAN_C_FLAGS_OPENGL_RELEASE "")
set(CONAN_CXX_FLAGS_OPENGL_RELEASE "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_RELEASE "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_RELEASE "")

# For modern cmake targets we use the list variables (separated with ;)
set(CONAN_C_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_CXX_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_SHARED_LINKER_FLAGS_OPENGL_RELEASE_LIST "")
set(CONAN_EXE_LINKER_FLAGS_OPENGL_RELEASE_LIST "")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE "${CONAN_FRAMEWORKS_OPENGL_RELEASE}" "_OPENGL" "_RELEASE")
# Append to aggregated values variable
set(CONAN_LIBS_OPENGL_RELEASE ${CONAN_PKG_LIBS_OPENGL_RELEASE} ${CONAN_SYSTEM_LIBS_OPENGL_RELEASE} ${CONAN_FRAMEWORKS_FOUND_OPENGL_RELEASE})


### Definition of global aggregated variables ###

set(CONAN_DEPENDENCIES_RELEASE glfw glad opengl)

set(CONAN_INCLUDE_DIRS_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/include"
			"C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/include" ${CONAN_INCLUDE_DIRS_RELEASE})
set(CONAN_LIB_DIRS_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/lib"
			"C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/lib" ${CONAN_LIB_DIRS_RELEASE})
set(CONAN_BIN_DIRS_RELEASE  ${CONAN_BIN_DIRS_RELEASE})
set(CONAN_RES_DIRS_RELEASE  ${CONAN_RES_DIRS_RELEASE})
set(CONAN_FRAMEWORK_DIRS_RELEASE  ${CONAN_FRAMEWORK_DIRS_RELEASE})
set(CONAN_LIBS_RELEASE glfw3 glad ${CONAN_LIBS_RELEASE})
set(CONAN_PKG_LIBS_RELEASE glfw3 glad ${CONAN_PKG_LIBS_RELEASE})
set(CONAN_SYSTEM_LIBS_RELEASE gdi32 opengl32 ${CONAN_SYSTEM_LIBS_RELEASE})
set(CONAN_FRAMEWORKS_RELEASE  ${CONAN_FRAMEWORKS_RELEASE})
set(CONAN_FRAMEWORKS_FOUND_RELEASE "")  # Will be filled later
set(CONAN_DEFINES_RELEASE  ${CONAN_DEFINES_RELEASE})
set(CONAN_BUILD_MODULES_PATHS_RELEASE  ${CONAN_BUILD_MODULES_PATHS_RELEASE})
set(CONAN_CMAKE_MODULE_PATH_RELEASE "C:/Users/thoma/.conan/data/glfw/3.3.6/_/_/package/d3cffeefc8c8bcb6be8abdd182cb1b56fc81bacc/"
			"C:/Users/thoma/.conan/data/glad/0.1.34/_/_/package/fb93620fa51fad15b528975c02ee36a641fb08eb/"
			"C:/Users/thoma/.conan/data/opengl/system/_/_/package/5ab84d6acfe1f23c4fae0ab88f26e3a396351ac9/" ${CONAN_CMAKE_MODULE_PATH_RELEASE})

set(CONAN_CXX_FLAGS_RELEASE " ${CONAN_CXX_FLAGS_RELEASE}")
set(CONAN_SHARED_LINKER_FLAGS_RELEASE " ${CONAN_SHARED_LINKER_FLAGS_RELEASE}")
set(CONAN_EXE_LINKER_FLAGS_RELEASE " ${CONAN_EXE_LINKER_FLAGS_RELEASE}")
set(CONAN_C_FLAGS_RELEASE " ${CONAN_C_FLAGS_RELEASE}")

# Apple Frameworks
conan_find_apple_frameworks(CONAN_FRAMEWORKS_FOUND_RELEASE "${CONAN_FRAMEWORKS_RELEASE}" "" "_RELEASE")
# Append to aggregated values variable: Use CONAN_LIBS instead of CONAN_PKG_LIBS to include user appended vars
set(CONAN_LIBS_RELEASE ${CONAN_LIBS_RELEASE} ${CONAN_SYSTEM_LIBS_RELEASE} ${CONAN_FRAMEWORKS_FOUND_RELEASE})
